import { describe, expect, it } from "vitest";
import {
  generateTacticalCacheKey,
  buildCanonicalTacticalKey,
  computeDeterministicHash,
  canonicalizeText,
} from "../../convex/lib/tacticalFingerprint.ts";
import {
  validateServerTacticalPlan,
  clampCoord,
} from "../../convex/lib/tacticalValidation.ts";

describe("Phase 3: Tactical AI Pipeline & Versioned Tactical Cache Suite", () => {
  describe("1. Deterministic Tactical Cache Fingerprinting (Rule 10)", () => {
    it("generates deterministic cache keys following 'drill-cache:v2:<fingerprint>' format", () => {
      const res = generateTacticalCacheKey({
        ageGroup: "U13-U14",
        category: "tactical_possession",
        difficulty: "Intermediate",
        pitchType: "full",
        targetAttribute: "Tactical",
        playerCount: 14,
        promptNotes: "High pressing 4-3-3 build-up",
      });

      expect(res.cacheKey).toMatch(/^drill-cache:v2:[0-9a-f]{16}$/);
      expect(res.fingerprint).toMatch(/^[0-9a-f]{16}$/);
      expect(res.canonicalKey).toContain("cat=tactical_possession");
      expect(res.canonicalKey).toContain("age=u13-u14");
    });

    it("ensures identical tactical parameters yield exactly identical fingerprints", () => {
      const run1 = generateTacticalCacheKey({
        ageGroup: "U15-U16",
        category: "passing_rondos",
        difficulty: "Advanced",
        promptNotes: "3rd man runs",
      });

      const run2 = generateTacticalCacheKey({
        ageGroup: "U15-U16",
        category: "passing_rondos",
        difficulty: "Advanced",
        promptNotes: "3rd man runs",
      });

      expect(run1.cacheKey).toBe(run2.cacheKey);
      expect(run1.fingerprint).toBe(run2.fingerprint);
    });

    it("normalizes case and whitespace so semantically identical requests match", () => {
      const key1 = generateTacticalCacheKey({
        ageGroup: "u11-u12",
        category: "Ball_Mastery",
        promptNotes: "  Fast   footwork in tight channel  ",
      });

      const key2 = generateTacticalCacheKey({
        ageGroup: "U11-U12",
        category: "ball_mastery",
        promptNotes: "Fast footwork in tight channel",
      });

      expect(key1.cacheKey).toBe(key2.cacheKey);
      expect(key1.fingerprint).toBe(key2.fingerprint);
    });

    it("generates distinct fingerprints when meaningful tactical parameters differ", () => {
      const base = {
        ageGroup: "U13-U14",
        category: "counter_attack",
        difficulty: "Intermediate",
        pitchType: "full",
        targetAttribute: "Speed",
        promptNotes: "Direct transition",
      };

      const keyBase = generateTacticalCacheKey(base);

      // Different category
      const keyDiffCat = generateTacticalCacheKey({ ...base, category: "passing_rondos" });
      expect(keyDiffCat.fingerprint).not.toBe(keyBase.fingerprint);

      // Different age group
      const keyDiffAge = generateTacticalCacheKey({ ...base, ageGroup: "U6-U8" });
      expect(keyDiffAge.fingerprint).not.toBe(keyBase.fingerprint);

      // Different pitch type
      const keyDiffPitch = generateTacticalCacheKey({ ...base, pitchType: "rondo_grid" });
      expect(keyDiffPitch.fingerprint).not.toBe(keyBase.fingerprint);

      // Different tactical prompt notes
      const keyDiffNotes = generateTacticalCacheKey({ ...base, promptNotes: "Low block defending" });
      expect(keyDiffNotes.fingerprint).not.toBe(keyBase.fingerprint);

      // Different player count
      const keyDiffCount = generateTacticalCacheKey({ ...base, playerCount: 22 });
      expect(keyDiffCount.fingerprint).not.toBe(keyBase.fingerprint);
    });
  });

  describe("2. AI Pipeline Validation & Normalization Boundary (Rule 6)", () => {
    it("rejects untrusted AI output with missing title or empty phases", () => {
      const malformedAiOutput = {
        drill: { title: "Incomplete AI Drill" },
        tacticalPlan: {
          title: "",
          phases: [],
        },
      };

      const res = validateServerTacticalPlan(malformedAiOutput.tacticalPlan);
      expect(res.valid).toBe(false);
      expect(res.errors.length).toBeGreaterThanOrEqual(1);
    });

    it("safely sanitizes out-of-bounds coordinates generated by AI to [0, 100]", () => {
      const aiPlanWithOutOfBounds = {
        title: "AI Generated Overlap Drill",
        pitchType: "attacking_half",
        phases: [
          {
            phaseNumber: 1,
            title: "Phase 1: Wing Overlap",
            durationSeconds: 6,
            players: [
              {
                id: "winger",
                team: "home",
                number: 11,
                position: { x: -30, y: 140 }, // Out of bounds
                targetPosition: { x: 120, y: 80 }, // Out of bounds
              },
            ],
            ball: { x: -10, y: 110, speed: "ground" },
            equipment: [],
            annotations: [],
          },
        ],
      };

      const res = validateServerTacticalPlan(aiPlanWithOutOfBounds);
      expect(res.valid).toBe(true);
      expect(res.normalizedPlan).toBeDefined();

      const p = res.normalizedPlan?.phases[0].players[0];
      expect(p?.position.x).toBe(0);
      expect(p?.position.y).toBe(100);
      expect(p?.targetPosition?.x).toBe(100);
      expect(p?.targetPosition?.y).toBe(80);

      const b = res.normalizedPlan?.phases[0].ball;
      expect(b?.x).toBe(0);
      expect(b?.y).toBe(100);
    });

    it("reconciles duplicate player IDs generated by AI within a single phase", () => {
      const aiPlanWithDuplicateIds = {
        title: "AI Plan With Duplicated Player IDs",
        phases: [
          {
            phaseNumber: 1,
            title: "Phase 1",
            durationSeconds: 4,
            players: [
              { id: "player_1", team: "home", number: 4, position: { x: 30, y: 40 } },
              { id: "player_1", team: "home", number: 5, position: { x: 30, y: 60 } }, // duplicate ID
            ],
            ball: { x: 30, y: 40 },
            equipment: [],
            annotations: [],
          },
        ],
      };

      const res = validateServerTacticalPlan(aiPlanWithDuplicateIds);
      expect(res.valid).toBe(false);
      expect(res.errors.some((e) => e.includes("Duplicate player ID"))).toBe(true);

      // Normalization safely guarantees uniqueness
      const players = res.normalizedPlan?.phases[0].players;
      expect(players).toBeDefined();
      expect(players![0].id).not.toBe(players![1].id);
    });

    it("bounds excessive phase duration from AI hallucination to max 300 seconds", () => {
      const aiPlanWithHugeDuration = {
        title: "AI Long Duration Drill",
        phases: [
          {
            phaseNumber: 1,
            title: "Phase 1",
            durationSeconds: 3600, // 1 hour phase hallucination
            players: [{ id: "p1", team: "home", position: { x: 50, y: 50 } }],
            ball: { x: 50, y: 50 },
            equipment: [],
            annotations: [],
          },
        ],
      };

      const res = validateServerTacticalPlan(aiPlanWithHugeDuration);
      expect(res.normalizedPlan?.phases[0].durationSeconds).toBe(300);
    });
  });
});
